### ISSUE TITLE
error in/from index.js

### ISSUE THREAD

**Issue by itsonlym3** [AdamMoses-GitHub/NPMJS-ap-top25-ncaaf#2]
i was getting the following error:
Usage example of the ap-top25-ncaaf package.
/home/pi/node_modules/cheerio/lib/parse.js:69
    var oldParent = node.parent || node.root,
                         ^

TypeError: Cannot read property 'parent' of null
    at Function.exports.update (/home/pi/node_modules/cheerio/lib/parse.js:69:26)
    at module.exports (/home/pi/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/home/pi/node_modules/cheerio/lib/static.js:27:14)
    at parseTop25Data (/home/pi/node_modules/ap-top25-ncaaf/index.js:47:33)
    at Request._callback (/home/pi/node_modules/ap-top25-ncaaf/index.js:146:34)
    at Request.self.callback (/home/pi/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/pi/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/pi/node_modules/request/request.js:1083:12)

modified index.js and issued a pull request.  hope that's ok!

**Comment by AdamMoses-GitHub** [comment]
fixed!
